[package]
name = "crab-talk"
version = "0.1.0"
edition = "2021"
authors = ["nacl42 <code@nacl42.de>"]
description = "yet another rust translation system"
repository = "https://github.com/nacl42/crab-talk"
keywords = ["i18n"]
license = "MIT or Apache-2.0"